### ISSUE TITLE
Does ng-admin supports normal ajax call instead of Rest call?

### ISSUE THREAD

**Issue by jslearner07** [marmelab/ng-admin#1046]
Hi,

Ng-admin is a great admin console, which works well with Rest service. But my legacy application has few screens which makes ajax calls for listview, edit etc and changing the ajax post urls to rest service will require code changes in various screens

So please let me know if I can use normal ajax call with Restangular or ng-admin. Basically I want to fire a normal ajax call on clicking the user or saving the user instead of rest call. If so, please let me know how will I do that

Thanks.

**Comment by sam2x** [comment]
Your use of "Ajax call" "Rest call" make non-sense for me. Since Restangular is an ajax library, it make ajax call to REST api. 
As well, Ng-admin is dedicated for REST api service endpoints. That means your endpoint must be "compliant" to REST :
- URI to identify ressources,
- HTTP Verbs as operation,
- Responses describes ressources (here json until you transform some other response format to json)

**Comment by jslearner07** [comment]
I know Rest call is happening as ajax call in case of ng-admin. 

May be the question framed by me is not correct. My actual requirement is sending the form params in terms of json object and not in terms of /fetch/v1/v2. Both GET as well as POST should be supported as we do in normal ajax calls when we send json object to controller.

Pls let me know if you have any solution for this.

**Comment by fzaninotto** [comment]
Whenever you have to do something that ng-admin doesn't do, use Angular directly. It is extremely powerful. Ng-admin makes its best to get out of the way when you don't need it.
