### ISSUE TITLE
incorrect documentation

### ISSUE THREAD

**Issue by Cantarella** [marmelab/ng-admin#1184]
Dear developers, such disgusting documentation as you have in the project I have not seen anywhere else. You give your product as a "black box" and still write incorrect documentation for customization!
Example:
*
import NumberField from 'admin-config/lib/Field/NumberField';
class AmountField extends NumberField {
    constructor(name) {
        super(name);
        this._currency = '$';
    }
    currency(currency) {
        if (!arguments.length) return this._currency;
        this._currency = currency;
        return this;
    }
}
export default AmountField;
*/

However, if I do exactly as you suggest then the system will fail, because your component is waiting a constructor from me, that will be stored directly in registered through a provider, same name property. I.e. export should be as flws: exports["default"] = my class ; module.exports = exports["default»];

You further advise on the creation of a widget for a custom field type and again give incorrect advice on how to connect. In this case, errors in the console drop out incoherently: a[y] is not a function  or: e_typeField is not constructor.

An these are only few of many examples of errors. There are too much errors, literally on every page. I am very disappointed that got involved with your product.

**Comment by jpetitcolas** [comment]
Dear embittered developer,

> You give your product as a "black box"...

Thanks for using our **open-source** project. Because, yes, you have access to the whole code source and documentation on GitHub. We promise (and you can check it), there is no hidden call to our servers, nor keylogging features to steal your data. We just released it for free (as in beer and as in software) to help the community releasing awesome projects with less efforts.

> ...and still write incorrect documentation for customization.

We are sorry to hear that. Indeed, we are humans, and are committing some mistakes. Yet, we swear we are doing our best to deliver the most up-to-date and error prone documentation ever. If you detect some errors, feel free to submit a pull request. It would take far less time than writing such a long and constructive issue, and would be useful to everyone. 

>  i.e. export should be as flws: exports["default"] = my class ; module.exports = exports["default»];

I am not sure to understand well your problem however. Is the `module.exports` missing in your code in order to make it work? If so, that's more a Babel transpilation issue. Indeed, we should mention if requires the `babel-plugin-add-module-exports` plug-in. That's a good idea. We are going to add it in the documentation shortly. :)

As a final note, just remember we are a team of volunteers spending some of our time on this open-source product, for free.  ;)

**Comment by ValentinKlinghammer** [comment]
You guys build a very useful tool and I for one am very grateful for your efforts!

Thanks!
