### ISSUE TITLE
What happened to the support

### ISSUE THREAD

**Issue by avifatal** [marmelab/ng-admin#1217]
Hi
I have posted 3 issues few weeks ago but did not get any respond.
What happened?

Is this project still running?

Thanks

**Comment by jpetitcolas** [comment]
Hi @avifatal,

We are working on this open-source project (among others) generally on our free time, on a voluntary basis. We indeed have some delay about pull requests processing. But this project is still alive! We will continue to support it, fixing critical bugs. We are using it on several production projects after all.

Yet, the amount of work is important, especially to inspect in details every issue. Even if the community helps (via [Gitter](https://gitter.im/marmelab/ng-admin), [StackOverflow](http://stackoverflow.com/questions/tagged/ng-admin), etc.), there are definitively some bugs we need to address. If an issue is really critical, do not hesitate to submit a pull request. :)

Moreover, as you may have noticed, we released several versions of ng-admin recently (some of them were broken because of a major change in way code is embedded). That's not proves of a dead project. :)

Also note that we are currently gathering some issues to label for the [Hacktober Fest](https://hacktoberfest.digitalocean.com/). It should help reducing number of issues. 

Have a good day!
