### ISSUE TITLE
Bower install doesn't include built js files

### ISSUE THREAD

**Issue by Joe-Edwards** [marmelab/ng-admin#1302]
Running `bower install ng-admin` produces the following output

```
$ bower install ng-admin
bower ng-admin#*            not-cached https://github.com/marmelab/ng-admin.git#*
bower ng-admin#*               resolve https://github.com/marmelab/ng-admin.git#*
bower ng-admin#*              download https://github.com/marmelab/ng-admin/archive/v1.0.0.tar.gz
bower ng-admin#*               extract archive.tar.gz
bower ng-admin#*          invalid-meta for:<temp>\bower\555d52cad249a1affc4894a9bfc2c673-2344-9ElP6W\bower.json
bower ng-admin#*          invalid-meta The "main" field cannot contain minified files
bower ng-admin#*          invalid-meta The "main" field cannot contain minified files
bower ng-admin#*              resolved https://github.com/marmelab/ng-admin.git#1.0.0
bower ng-admin#^1.0.0          install ng-admin#1.0.0

ng-admin#1.0.0 bower_components\ng-admin
```

bower.json shouldn't refer to minified files, as per the [spec](https://github.com/bower/spec/blob/master/json.md), however I believe those are 'just' warnings.

However, the bigger problem is that the 'build' directory no longer exists:

```
$ ls bower_components/ng-admin/
_postinstall.js  bower.json  CHANGELOG.md  doc/  ISSUE_TEMPLATE.md  LICENSE  README.md  scripts/  SUMMARY.md  webpack.config.js
```

It was removed in 4f00e8f4bc812871b88e3061fdeb77d4ee9c9e6a without much explanation. This means that there are no usable JS files installed.

**Comment by Kmaschta** [comment]
Hi,

Sorry we didn't communicate a lot about this, but we don't support Bower anymore.
I've updated the documentation in my PR https://github.com/marmelab/ng-admin/pull/1303

You can still install ng-admin with `npm` or `yarn`.

**Comment by michael1688** [comment]
Hi,

It is very sad to hear this news. Is this the final decision to stop supporting Bower on ng-admin? 
As my understand, there are many projects using Bower as frontend dependencies manager. Without supporting Bower, it will be inconvenient and incomplete for such good module. Thanks,

Michael

**Comment by Kmaschta** [comment]
As you can read on our [blog post about the ng-admin release](https://marmelab.com/blog/2017/01/27/ngadmin-1.0-is-out.html), it relies on an outdated technology (Angular 1.4) and we are not optimally focusing on ng-admin in favor of [others many open-source projects](https://github.com/marmelab).

Since we are clearly in a "maintenance and security only" mode, we really don't plan to support bower since it will add to the maintenance complexity.

But if you are interested in an admin GUI sponsored by marmelab, you can take a look to [admin-on-rest](https://github.com/marmelab/admin-on-rest)!
