### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by narigua** [marmelab/ng-admin#169]
Hi the team !

What do you plan for translation in ng-admin ? Because many of words are directly implement in your app.

**Comment by narigua** [comment]
Hi,

For my app, i use this https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/doc/index.md

It could be good for your solution, because all JS part are AMD ready, and for all Symfony2 users this bundle it's just beautifull.

**Comment by sgimeno** [comment]
@narigua I'm not sure that Symfony2 has to influence ng-admin design decisions, it should stay as a frontend javascript library IMO.

What do you think of using [angular-gettext](angular-gettext.rocketeer.be) for translations? I think a .pot file could be distributed with the ng-admin dist files and users would only need to create their own .po files with Poedit. Optionally ng-admin could maintain and distribute some .po files for common translations.

Obviously it adds a dependency to the project, but at least is an Angular one.

**Comment by fzaninotto** [comment]
angular-gettext is a great suggestion. @sgimeno , would you like to start working on an implementation on ng-admin?

**Comment by Xennis** [comment]
Another suggestion would be [angular-translate](https://github.com/angular-translate/angular-translate), which uses JSON files instead of .po files.

**Comment by sgimeno** [comment]
I've been diving a little into the issue, did a [proof of concept](https://github.com/sgimeno/ng-admin/tree/angular-gettext) using `angular-gettext`. It has its pros and cons. @Xennis I don't know about angular-translate but we should discuss the use cases and compare all solutions. 

Here's the summary: 

# Translations

You can translate all application strings using [angular-gettext](https://angular-gettext.rocketeer.be)

We provide a `template.pot` file where annotated strings like "Dashboard" have been extracted. Follow
angular-gettext instructions to generate a `translations.js` file and add it to your `index.html`.


### Notes

Translations are made by lib consumers, this is more flexible but more work for lib consumers, opinions are welcome.

I've added `angular-gettext` and `grunt-angular-gettext` as new bower and npm dependencies. `template.pot` file is generated using `grunt extract`. Lib users will still need to use `grunt-angular-gettext` to compile their translations from their .po files.

For this proof of concept I've created 2 dummy translations with Poedit to translate the "Dashboard" page header to French or Spanish depending on browser language. Translations are located at `examples/blog/translations/`.

English is the fallback language and ng-admin is deciding which translation to show between (fr|es) using this ugly logic trying to figure out user language:

```javascript
MainModule.run(function (gettextCatalog) {
  gettextCatalog.debug = true;
  //Workaround for cross-browser language detection
  var re = new RegExp('^([a-z]{2})(?:-[A-Z]{2})?$', 'i');
  var userLanguage = re.exec(navigator.language).pop();
  gettextCatalog.setCurrentLanguage(userLanguage);
});
```
Maybe this logic should be delegated to lib users?

It's important to note that language selection made by angulat-gettext is based on the data of .po files not the name of the file, but Poedit makes them coincident for simplicity.

**Comment by sgimeno** [comment]
@Xennis @fzaninotto any feedback on this?

**Comment by fzaninotto** [comment]
Sorry, my backlog is kinda full lately. I will need some time to review your proof-of-concept and give you feedback. In the meantime, fell free to discuss it further with @Xennis.

**Comment by Xennis** [comment]
@sgimeno I read through your commit and for me it looks not bad. In general I've not so much experience with Angular in combination with translation/internationalization. I used angular-translate for the first time some days ago to translate an Angular module. I googled a little bit about angular-gettext and angular-translation. Be careful, hence this is not an expert, just an "googled option":
* *angular-translate* is more complex, since it has several features (like use cookies to remember settings, load translation from a server, etc.) and supports several options e.g. different namespaces. But the most of these big features are Angular modules by itself, so you only include them when you need them. The translation is in JS or JSON.
* *angular-gettext* on the other side is more lightweight and easier. The translation is in .po files.

The usage is quite simular. In both you can use the syntax `<h1 translate>Dashboard</h1>` . I don't know the core architecture of ng-admin well, but I would go with both and especially your concept.

**Comment by sgimeno** [comment]
@Xennis The usage and concept are quite similar for both libs so I guess there's no big deal on using one or another. That said I think the interesting decisions to make here are:

+ Translations should be configurable by lib users?
+ If so, which format, JSON, .po, both? Should we provide default translations anyways?
+ If not, we should provide default translations, so is this maintainable/scalable for a large number of languages? How do we we distribute translation files, etc?

I guess we can make an initial solution and ask some feedback to users. It would be good to know how many people is interested on this as well as Angular 2 is about to land and might low down all angular1 modules interest.

**Comment by Xennis** [comment]
> Translations should be configurable by lib users?

Yes, I think the user should always have the possibility for configuration. E.g. may a user wants to use a more polite or a more youth slang translation.
> * If so, which format, JSON, .po, both? Should we provide default translations anyways?
> * If not, we should provide default translations, so is this maintainable/scalable for a large number of languages? How do we we distribute translation files, etc?

It should be a format, which is easy to edit. Hard to say, different options:
* Provide only the English version in this repo, which is always up to date. Put all all other translations in an ng-admin language files repo, since they are may not always up to date or well maintained. Then users can contribute to this repo to update and add translation files.
* Put all translation files in this repo. For this case if a language string in a specif translation is not found, there should be a fallback  to the English translation / no translation (`<h1 translate>Dashboard</h1>`).

**Comment by fedotxxl** [comment]
+1 for i18n. I'm from java world and we don't use `.po` files (I think a lot of other developers too) so angular-translate looks like more universal solution for me

**Comment by fzaninotto** [comment]
The implementation of ng-admin translation (using `angular-translate`) has begun!

**Comment by ganlhi** [comment]
Hello there !

Is there a way to add a translation (a French one, actually) when configuring ng-admin in my app?

Thanks.

**Comment by fzaninotto** [comment]
Yep, see https://github.com/marmelab/ng-admin/blob/master/doc/Translation.md

**Comment by ganlhi** [comment]
Hello,

Thank you for the answer. It is what I expected, but I am unable to make it
work because Angular  says it doesn't know $translateProvider when I try to
inject it in my config function. I also tried to list 'pascalprecht.translate'
module as a direct dependency of my app, but it doesn't find it either...
