### ISSUE TITLE
Ability to create custom create/edit field

### ISSUE THREAD

**Issue by thangngoc89** [marmelab/ng-admin#208]
I want to add a color picker to my ng-admin dashboard.
I use this module to do it [angular-bootstrap-colorpicker](https://github.com/buberdds/angular-bootstrap-colorpicker)
But the problem is in Create/Edit view. ng-admin doesn't send input value into server.
How can I do that? 
Is it possible to add custom attribute to a Field?

**Comment by cvlmtg** [comment]
I think my problem is similar. Since it seems ng-admin date field doesn't provide the option to input time as well, I'm trying to use an angular datetime input field with the 'template' Field type, however I currently have 2 problems. the first is that I have no idea how to make it display a value (it sends it to the server when I save the model though), the second is that on the show view it keeps displaying the input field instead of just showing the value. I understand this is due to the fact that the 'template' Field was designed as a way to display buttons (which are expected to be displayed on the show view too) but I think it is important to allow users to put custom input fields, as ng-admin doesn't provide a solution for every possible input value.

**Comment by thangngoc89** [comment]
Hum. I have to edit ng-admin source to add a single attribute in input tag. I hope ng-admin will send all input available to the server

**Comment by fzaninotto** [comment]
We've successfully created a custom datetime picker using a template directive. Here is an extract of the code:

```js
fooEntity.editionView()
    .addField(new Field('publication_date')
        .type('template')
        .template('<datetime-picker></datetime-picker>')
        .validation({ required: true }
    ))
```

Then we define the custom datetimePicker directive as follows:

```js
(function(angular) {
  'use strict';

  angular.module('myModule').directive('datetimePicker', ['$filter', function ($filter) {
    return {
      restrict: 'E',
      replace: false,
      link: function(scope, element, attr) {
        var datetimepicker = element.datetimepicker({
          defaultDate: $filter('date')(scope.entry.values[scope.field.name()], 'dd/MM/yyyy HH:mm')
        });
        datetimepicker.on("change.dp", function(e) {
          scope.entry.values[scope.field.name()] = $(element).data("DateTimePicker").getDate();
          scope.$digest();
        });
      },
      template: '<div class="input-group date">' +
    '<input type="text" class="form-control" data-date-format="DD/MM/YYYY HH:mm"/>' +
    '<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>' +
    '</div>'
    };
  }]);
}(angular));
```

And it works fine. No need to edit the ng-admin source. There are even more elegant solutions (using isolated scope).

**Comment by fzaninotto** [comment]
By the way we're using `eonasdan-bootstrap-datetimepicker`. We're considering adding the datetime field type in the near future.

**Comment by thangngoc89** [comment]
@fzaninotto thank you for your reply. I'm a bit new to Angular.JS. I'm digging your code right now.

**Comment by cvlmtg** [comment]
thank you very much too! :) I'm an angular newbie too and learning both ng-admin and angular at the same time is not easy. adding such an example at the docs would be a huge help for people like me.
thanks again for the help.
