### ISSUE TITLE
Search in field on <th>

### ISSUE THREAD

**Issue by narigua** [marmelab/ng-admin#219]
What do you think about an option to add filterquery in <th> by field ?

**Comment by fzaninotto** [comment]
Already implemented, see https://github.com/marmelab/ng-admin/blob/349a94d4e5444024bc9a105b289c728435f462c9/src/javascripts/config-dist.js#L212.

It won't appear on TH, but on a div above the table (see demo)

**Comment by narigua** [comment]
I see it, really good job, but my question was on a search field on TH, will be very user friendly ;)

**Comment by fzaninotto** [comment]
Search field on TH is not user friendly IMO. For instance, on a date field, you probably want to offer an interval selector, which will probably take more screen real estate than the column itself. Symmetrically, you often don't need to offer filters for some columns. For instance, it's a good practice to offer a single 'full text' filter for all text columns, rather than one for each column.

**Comment by narigua** [comment]
Good arguments ;)
