### ISSUE TITLE
Cure UI-Router infinite loop 

### ISSUE THREAD

**Issue by osiloke** [marmelab/ng-admin#312]
UI-Router appears to have a bug as mentioned at https://github.com/angular-ui/ui-router/issues/600. It causes an infinite loop when you try to modify the state in the statechangestart event. 

There is a workaround. It would be nice to add to the project
```
$urlRouterProvider.otherwise( function($injector, $location) {
            var $state = $injector.get("$state");
            $state.go("dashboard");
        });
```

**Comment by fzaninotto** [comment]
Can you be more specific about the use case that would justify changing the state in the statechangestart event?

Also, the ng-admin router already does `$urlRouterProvider.otherwise('/dashboard');`. If your snippet solves a but, would you mind submitting a PR with the snippet and an e2e test demonstrating the bug?

**Comment by rainboxx** [comment]
We're having this issue, too. We don't have a state for '/' and redirect to a initial state, which will end in an infinite digest loop.

**Comment by rainboxx** [comment]
Sorry, I wanted to comment this on the angular-ui repo...

**Comment by fzaninotto** [comment]
Ne feedback for a few months, closing.
