### ISSUE TITLE
How to get filtred data in custom page controller?

### ISSUE THREAD

**Issue by PaulMaly** [marmelab/ng-admin#326]
Hello! It's not an issue,is more a question.

I've list view with filters. I need to create some custom page, where I could use filtered data list on it. 

Simple user story:
1) select some filters on list view page
2) filtred data list appears
3) go to custom page and use filtered data set on it

Can someone provide me a code snippet how I able to do that?

**Comment by fzaninotto** [comment]
There is [a dedicated doc section about custom pages](https://github.com/marmelab/ng-admin/blob/master/doc/Custom-pages.md#adding-custom-pages). I suggest you pass the `search` param (taken from the URI) to this new page, and fetch the API again with this filter (because you probably don't want the pagination).  

You can also look at @ThieryMichel's work on the CSV export button: https://github.com/marmelab/ng-admin/pull/316
