### ISSUE TITLE
issue with ng-annotate 0.10.0

### ISSUE THREAD

**Issue by ThieryMichel** [marmelab/ng-admin#373]
ng-admin trigger the error:
```Unknown provider: aProvider <- a <- dateParser <- datepickerPopupDirective```
When using ng-annotate 0.10.0.
The error disappear, if we put ng-annotate dependency to 0.4.0, and build using node 0.10

**Comment by fzaninotto** [comment]
Fixed by 76ee25ef3e1e7426815351dc448540a5878eabba

**Comment by bes89** [comment]
i upgraded ng-annotate to 0.10 because i couldn't build ng-admin:
```bash
~/ng-admin(branch:0.6.0-extended-validators*) » make build
Running "requirejs:prod" (requirejs) task

Running "ngAnnotate:ngadmin" (ngAnnotate) task
Warning: Cannot assign to read only property '$methodName' of false Use --force to continue.

Aborted due to warnings
```
see: https://github.com/olov/ng-annotate/issues/139

if i downgrade to 0.4 i can not build ng-admin with my modifications and if i use ng-annotate 0.10 i get the error message `Unknown provider: aProvider <- a <- dateParser <- datepickerPopupDirective`

It must work with a newer version of ng-annotate... please reopen

**Comment by fzaninotto** [comment]
@ThieryMichel Is it still a problem?
