### ISSUE TITLE
Import into new environment fails

### ISSUE THREAD

**Issue by nheinbaugh** [marmelab/ng-admin#504]
Hey guys,

Yesterday I was putting together a quick POC using the tutorial. And it worked like a charm. So today I went to start adding ng-admin to my sails application. I bower install'd it and then when I added the references to the html page I started getting "cannot get property 'isDefined' of undefined".

Since I haven't added any logic or anything I'm guessing this has something to do with the commits from today. Any thoughts?

**Comment by fzaninotto** [comment]
ping @jeromemacias is everything rebuilt correctly?

**Comment by jeromemacias** [comment]
Seems ok for me on my local env for the blog example.

**Comment by nheinbaugh** [comment]
Hey,

I'm still getting a failure when I am just creating a basic sails app. I have uploaded it to github if you could see what is going on I would appreciate it.

https://github.com/nheinbaugh/Ng-Admin-Test

Thanks,
Nick

**Comment by jeromemacias** [comment]
Based on your layout: https://github.com/nheinbaugh/Ng-Admin-Test/blob/6a296c00b07b43f0e80f991398177e5cac8f1830/views/layout.ejs#L95-L125

You should:
* Include `/js/build/ng-admin-only.min.js` instead of `/js/build/ng-admin.min.js`
* Include `/js/build/ng-admin-only.min.js` after all other scripts
* Include `/js/ng-file-upload.js` instead of `/js/angular-file-upload.js`

**Comment by Shazam14** [comment]
@nheinbaugh does the answer above solved your issue?
