### ISSUE TITLE
For required boolean field, keep the checkbox

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/ng-admin#683]

**Comment by F3L1X79** [comment]
I guess you mean the checkboxes but I do agree a lot with this one :+1:

**Comment by jpetitcolas** [comment]
No, radio buttons. It is either `true` or `false`. It is not a Schrödinger boolean. :)

**Comment by jpetitcolas** [comment]
Oh, I see what you meant. A single checkbox: checked is true, unchecked is false. Didn't remember. Yes then. :)

**Comment by F3L1X79** [comment]
Since https://github.com/marmelab/ng-admin/pull/629 , yup.

**Comment by fzaninotto** [comment]
I don't agree. This should remain a true/false choice, but with a validator to refuse empty submissions.

**Comment by F3L1X79** [comment]
Yes, but I think most users will prefer a checkbox over a dropdown for a required boolean - it is faster to use and way more eye friendly. 
@fzaninotto , I get your point but I think it's a shame to force developpers using a template instead of a feature they probably won't use?
Of course I won't argue anymore, it was just my point of view.

**Comment by fzaninotto** [comment]
How can you validate that a checkbox control is filled?

On the other hand, nothing prevents you from using a template type, or creating you own custom type.

**Comment by jpetitcolas** [comment]
For validation, using radio buttons would be fine. If no radio is checked, then the value is not filled.

**Comment by F3L1X79** [comment]
Yeah you're all right, validation will still be a problem with checkboxes... Nevermind my last comments.

**Comment by fzaninotto** [comment]
So I guess it's a duplicate of #527
