### ISSUE TITLE
ngTree as feature

### ISSUE THREAD

**Issue by sajov** [marmelab/ng-admin#925]
would be great

**Comment by fzaninotto** [comment]
So many things would be great! For instance: stopping the war in Syria, or finding a theory about quantum relativity. Unfortunately, I'm too occupied already because of the martian invasion that I have to fight.

But YOU, as a web developer, have the power to add ngTree as a feature. Yes, YOU. So stop asking and start doing. That's how open-source works.

**Comment by sajov** [comment]
you are totally right. I don't have angular experience and never saw webpack in action before. I mean i can't work it out. I thought suggest something could help open-source projects too. Sorry that i get you sound like that.
